"""MMseqs2 backend wrappers for clustering and output parsing."""

from __future__ import annotations

import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class MMseqs2ClusterPaths:
    """Output paths generated by an MMseqs2 easy-cluster execution."""

    tmp_dir: Path
    fasta_path: Path
    cluster_tsv: Path
    rep_fasta: Path


def _which_mmseqs() -> str:
    exe = shutil.which("mmseqs")
    if not exe:
        msg = "mmseqs executable not found in PATH. Install MMseqs2 and ensure `mmseqs` is available."
        raise FileNotFoundError(msg)
    return exe


def write_fasta(seqs: dict[str, str], fasta_path: Path) -> None:
    """Write sequence records to a FASTA file."""
    with fasta_path.open("w", encoding="utf-8") as f:
        for sid, seq in seqs.items():
            f.write(f">{sid}\n{seq}\n")


def run_mmseqs_easy_cluster(
    fasta_path: Path,
    out_prefix: Path,
    tmp_dir: Path,
    min_seq_id: float,
    coverage: float,
    cov_mode: int = 0,
    cluster_mode: int = 0,
    threads: int = 4,
    extra_args: list[str] | None = None,
) -> MMseqs2ClusterPaths:
    """Run MMseqs2 easy-cluster and collect expected output file paths."""
    mmseqs = _which_mmseqs()

    tmp_dir.mkdir(parents=True, exist_ok=True)
    out_prefix.parent.mkdir(parents=True, exist_ok=True)

    cmd = [
        mmseqs,
        "easy-cluster",
        str(fasta_path),
        str(out_prefix),
        str(tmp_dir),
        "--min-seq-id",
        str(min_seq_id),
        "-c",
        str(coverage),
        "--cov-mode",
        str(cov_mode),
        "--cluster-mode",
        str(cluster_mode),
        "--threads",
        str(threads),
    ]
    if extra_args:
        cmd.extend(extra_args)

    proc = subprocess.run(cmd, capture_output=True, text=True, check=False)  # noqa: S603
    if proc.returncode != 0:
        msg = f"MMseqs2 failed.\nCommand: {' '.join(cmd)}\nSTDOUT:\n{proc.stdout}\nSTDERR:\n{proc.stderr}\n"
        raise RuntimeError(msg)

    # MMseqs2 naming convention for easy-cluster
    cluster_tsv = Path(str(out_prefix) + "_cluster.tsv")
    rep_fasta = Path(str(out_prefix) + "_rep_seq.fasta")

    if not cluster_tsv.exists():
        msg = f"Expected cluster TSV not found: {cluster_tsv}"
        raise FileNotFoundError(msg)
    if not rep_fasta.exists():
        msg = f"Expected representative FASTA not found: {rep_fasta}"
        raise FileNotFoundError(msg)

    return MMseqs2ClusterPaths(
        tmp_dir=tmp_dir,
        fasta_path=fasta_path,
        cluster_tsv=cluster_tsv,
        rep_fasta=rep_fasta,
    )


def parse_cluster_tsv(cluster_tsv: Path) -> dict[str, str]:
    """Parse an MMseqs2 cluster TSV into member-to-representative mapping."""
    mapping: dict[str, str] = {}
    with cluster_tsv.open("r", encoding="utf-8") as f:
        for raw_line in f:
            line = raw_line.strip()
            if not line:
                continue
            rep, member = line.split("\t")[:2]
            mapping[member] = rep
    return mapping


def build_cluster_ids(member_to_rep: dict[str, str]) -> dict[str, str]:
    """Build stable cluster IDs from representative assignments."""
    return {member: f"mmseqs2:{rep}" for member, rep in member_to_rep.items()}
