"""Convert ESM2 embedding CSV to embeddings.npy + embedding_ids.csv.

Requires: demo_esm2_t6_8M_UR50D.csv (generated by using_sylphy_to_get_demo_embedding.sh)
Run from examples/raw_data_examples/
Output: embeddings.npy, embedding_ids.csv
"""

import numpy as np
import pandas as pd

df_emb = pd.read_csv("demo_esm2_t6_8M_UR50D.csv")
np.save("embeddings.npy", df_emb.drop(columns=["sequence"]).values)
print(f"Saved embeddings.npy {df_emb.drop(columns=['sequence']).shape}")

df_main = pd.read_csv("biosieve_example_dataset_1000.csv")
ids = df_main["id"].astype(str).tolist()
pd.DataFrame({"id": ids}).to_csv("embedding_ids.csv", index=False)
print(f"Saved embedding_ids.csv ({len(ids)} rows)")
