"""Convert ESM2 embedding CSV to embeddings.npy + embedding_ids.csv.

Requires: demo_esm2_t6_8M_UR50D.csv (generated by using_sylphy_to_get_demo_embedding.sh)
Run from examples/raw_data_examples/
Output: embeddings.npy, embedding_ids.csv
"""

import numpy as np
import polars as pl

df_emb = pl.read_csv("demo_esm2_t6_8M_UR50D.csv")
emb_array = df_emb.drop("sequence").to_numpy()
np.save("embeddings.npy", emb_array)
print(f"Saved embeddings.npy {emb_array.shape}")

df_main = pl.read_csv("biosieve_example_dataset_1000.csv")
ids = df_main["id"].cast(pl.String).to_list()
pl.DataFrame({"id": ids}).write_csv("embedding_ids.csv")
print(f"Saved embedding_ids.csv ({len(ids)} rows)")
